name: Manual pull and push

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull from Overleaf
      env:
        OVERLEAF_TOKEN: ${{ secrets.OVERLEAF_TOKEN }}
        OVERLEAF_PROJECT_ID: ${{ secrets.OVERLEAF_PROJECT_ID }}
      run: |
        git config pull.rebase false
        git pull https://git:${OVERLEAF_TOKEN}@git.overleaf.com/${OVERLEAF_PROJECT_ID} master

    - name: Push to GitHub overleaf branch
      run: |
        git checkout overleaf || git checkout -b overleaf
        git push --allow-unrelated-histories origin overleaf