# ワークフローの名前
name: Lint TeX files

# ワークフローの実行トリガー
on:
  pull_request:

jobs:
  # textlintを実行するジョブ
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node.jsの環境をセットアップ
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # 3. 依存パッケージのインストール
      # action-textlintが内部で 'npm ci' を実行するため、
      # このステップは必須ではありませんが、明示的に記述しておくと挙動が分かりやすくなります。
      - name: Install Dependencies
        run: npm ci

      # 4. textlintを実行し、PRにレビューコメントとして投稿
      - name: Run textlint
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          textlint_flags: "tex/"
          # --- ★最重要修正点 ---
          # 'added' (追加された行のみ) から 'nofilter' (フィルターなし) に変更。
          # これにより、tex/ ディレクトリ内のすべてのエラーが報告されるようになります。
          filter_mode: nofilter
